exercism/sqlite

- config.json
- exercises/practice/hello-world/.docs/instructions.md
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/hello-world/.meta/example.sql
- exercises/practice/hello-world/.meta/tests.toml
- exercises/practice/hello-world/create_fixture.sql
- exercises/practice/hello-world/hello-world.sql
- exercises/practice/hello-world/hello-world_test.sql
Feel free to test the exercise and comment about the setup.
> feat: add hello.-world exercise

- exercises/practice/hello-world/hello-world_test.sql
Single quotes have to be escaped with another single quote.
https://stackoverflow.com/a/70414773/4919081
> fix: unquoted single quotes

- .github/workflows/test.yml
- bin/run.sh
- bin/verify-exercise-example
- bin/verify-exercises
That is a first for me, adding workflows.
How can we test that?
> ci: add exercise testing ci

- docs/INSTALLATION.md
I think I covered the most common system architectures, right?
> docs: add installation guide

- exercises/practice/allergies/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/darts/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/eliuds-eggs/.meta/config.json
- exercises/practice/gigasecond/.meta/config.json
- exercises/practice/grains/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/high-scores/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/luhn/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/resistor-color-duo/.meta/config.json
- exercises/practice/resistor-color/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
- exercises/practice/yacht/.meta/config.json
Unless we decide for a cleaner way to show tests, this is the version that we had in mind at the beginning, now available for all exercises.
For further discussion please also see #54
> feat: show data and test_table in web-editor

- config.json
After merging #55 and #57 the track is ready to go live.
> feat: activate track

- exercises/practice/allergies/.meta/example.sql
- exercises/practice/allergies/allergies_test.sql
- exercises/practice/allergies/create_fixture.sql
- exercises/practice/allergies/test_reporter.sql
- exercises/practice/allergies/test_setup.sql
> Auto-format allergies .sql files

- exercises/practice/triangle/.meta/example.sql
- exercises/practice/triangle/create_fixture.sql
- exercises/practice/triangle/create_test_table.sql
- exercises/practice/triangle/triangle_test.sql
> Auto-format triangle .sql files

- exercises/practice/twelve-days/.meta/example.sql
- exercises/practice/twelve-days/create_fixture.sql
- exercises/practice/twelve-days/create_test_table.sql
- exercises/practice/twelve-days/twelve-days_test.sql
> Auto-format twelve-days .sql files

- exercises/practice/word-count/.meta/example.sql
- exercises/practice/word-count/create_fixture.sql
- exercises/practice/word-count/create_test_table.sql
- exercises/practice/word-count/word-count_test.sql
> Auto-format word-count .sql files

- exercises/practice/anagram/.meta/example.sql
- exercises/practice/anagram/anagram.sql
- exercises/practice/anagram/anagram_test.sql
- exercises/practice/anagram/create_fixture.sql
- exercises/practice/anagram/create_test_table.sql
> Auto-format anagram .sql files

- exercises/practice/armstrong-numbers/.meta/example.sql
- exercises/practice/armstrong-numbers/armstrong-numbers_test.sql
- exercises/practice/armstrong-numbers/create_fixture.sql
- exercises/practice/armstrong-numbers/test_reporter.sql
- exercises/practice/armstrong-numbers/test_setup.sql
> Auto-format armstrong-numbers .sql files

- exercises/practice/atbash-cipher/.meta/example.sql
- exercises/practice/atbash-cipher/atbash-cipher_test.sql
- exercises/practice/atbash-cipher/create_fixture.sql
- exercises/practice/atbash-cipher/create_test_table.sql
> Auto-format atbash-cipher .sql files

- exercises/practice/swift-scheduling/.meta/example.sql
- exercises/practice/swift-scheduling/create_fixture.sql
- exercises/practice/swift-scheduling/create_test_table.sql
- exercises/practice/swift-scheduling/swift-scheduling_test.sql
> Auto-format swift-scheduling .sql files

- exercises/practice/sublist/.meta/example.sql
- exercises/practice/sublist/create_fixture.sql
- exercises/practice/sublist/create_test_table.sql
- exercises/practice/sublist/sublist_test.sql
> Auto-format sublist .sql files

- exercises/practice/state-of-tic-tac-toe/.meta/example.sql
- exercises/practice/state-of-tic-tac-toe/create_fixture.sql
- exercises/practice/state-of-tic-tac-toe/create_test_table.sql
- exercises/practice/state-of-tic-tac-toe/state-of-tic-tac-toe_test.sql
> Auto-format state-of-tic-tac-toe .sql files

- exercises/practice/square-root/.meta/example.sql
- exercises/practice/square-root/create_fixture.sql
- exercises/practice/square-root/create_test_table.sql
- exercises/practice/square-root/square-root_test.sql
> Auto-format square-root .sql files

- exercises/practice/collatz-conjecture/.meta/example.sql
- exercises/practice/collatz-conjecture/collatz-conjecture_test.sql
- exercises/practice/collatz-conjecture/create_fixture.sql
- exercises/practice/collatz-conjecture/test_reporter.sql
- exercises/practice/collatz-conjecture/test_setup.sql
> Auto-format collatz-conjecture .sql files

- exercises/practice/roman-numerals/.meta/example.sql
- exercises/practice/roman-numerals/create_fixture.sql
- exercises/practice/roman-numerals/roman-numerals_test.sql
- exercises/practice/roman-numerals/test_reporter.sql
- exercises/practice/roman-numerals/test_setup.sql
> Auto-format roman-numerals .sql files

- exercises/practice/scrabble-score/.meta/example.sql
- exercises/practice/scrabble-score/create_fixture.sql
- exercises/practice/scrabble-score/create_test_table.sql
- exercises/practice/scrabble-score/scrabble-score_test.sql
> Auto-format scrabble-score .sql files

- exercises/practice/resistor-color/.meta/example.sql
- exercises/practice/resistor-color/create_fixture.sql
- exercises/practice/resistor-color/resistor-color_test.sql
- exercises/practice/resistor-color/test_reporter.sql
- exercises/practice/resistor-color/test_setup.sql
> Auto-format resistor-color .sql files

- exercises/practice/raindrops/.meta/example.sql
- exercises/practice/raindrops/create_fixture.sql
- exercises/practice/raindrops/raindrops_test.sql
- exercises/practice/raindrops/test_reporter.sql
- exercises/practice/raindrops/test_setup.sql
> Auto-format raindrops .sql files

- exercises/practice/resistor-color-duo/.meta/example.sql
- exercises/practice/resistor-color-duo/create_fixture.sql
- exercises/practice/resistor-color-duo/resistor-color-duo_test.sql
- exercises/practice/resistor-color-duo/test_reporter.sql
- exercises/practice/resistor-color-duo/test_setup.sql
> Auto-format resistor-color-duo .sql files

- exercises/practice/resistor-color-trio/.meta/example.sql
- exercises/practice/resistor-color-trio/create_fixture.sql
- exercises/practice/resistor-color-trio/create_test_table.sql
- exercises/practice/resistor-color-trio/resistor-color-trio_test.sql
> Auto-format resistor-color-trio .sql files

- exercises/practice/rest-api/.meta/example.sql
- exercises/practice/rest-api/create_fixture.sql
- exercises/practice/rest-api/create_test_table.sql
- exercises/practice/rest-api/rest-api_test.sql
> Auto-format rest-api .sql files

- exercises/practice/reverse-string/.meta/example.sql
- exercises/practice/reverse-string/create_fixture.sql
- exercises/practice/reverse-string/create_test_table.sql
- exercises/practice/reverse-string/reverse-string_test.sql
> Auto-format reverse-string .sql files

- exercises/practice/meetup/.meta/example.sql
- exercises/practice/meetup/create_fixture.sql
- exercises/practice/meetup/meetup_test.sql
- exercises/practice/meetup/test_reporter.sql
- exercises/practice/meetup/test_setup.sql
> Auto-format meetup .sql files

- exercises/practice/pascals-triangle/.meta/example.sql
- exercises/practice/pascals-triangle/create_fixture.sql
- exercises/practice/pascals-triangle/pascals-triangle_test.sql
- exercises/practice/pascals-triangle/test_reporter.sql
- exercises/practice/pascals-triangle/test_setup.sql
> Auto-format pascals-triangle .sql files

- exercises/practice/pig-latin/.meta/example.sql
- exercises/practice/pig-latin/create_fixture.sql
- exercises/practice/pig-latin/create_test_table.sql
- exercises/practice/pig-latin/pig-latin_test.sql
> Auto-format pig-latin .sql files

- exercises/practice/matching-brackets/.meta/example.sql
- exercises/practice/matching-brackets/create_fixture.sql
- exercises/practice/matching-brackets/matching-brackets_test.sql
- exercises/practice/matching-brackets/test_reporter.sql
- exercises/practice/matching-brackets/test_setup.sql
> Auto-format matching-brackets .sql files

- exercises/practice/leap/.meta/example.sql
- exercises/practice/leap/create_fixture.sql
- exercises/practice/leap/leap_test.sql
- exercises/practice/leap/test_reporter.sql
- exercises/practice/leap/test_setup.sql
> Auto-format leap .sql files

- exercises/practice/kindergarten-garden/.meta/example.sql
- exercises/practice/kindergarten-garden/create_fixture.sql
- exercises/practice/kindergarten-garden/kindergarten-garden_test.sql
- exercises/practice/kindergarten-garden/test_reporter.sql
- exercises/practice/kindergarten-garden/test_setup.sql
> Auto-format kindergarten-garden .sql files

- exercises/practice/isogram/.meta/example.sql
- exercises/practice/isogram/create_fixture.sql
- exercises/practice/isogram/isogram_test.sql
- exercises/practice/isogram/test_reporter.sql
- exercises/practice/isogram/test_setup.sql
> Auto-format isogram .sql files

- exercises/practice/darts/.meta/example.sql
- exercises/practice/darts/create_fixture.sql
- exercises/practice/darts/darts_test.sql
- exercises/practice/darts/test_reporter.sql
- exercises/practice/darts/test_setup.sql
> Auto-format darts .sql files

- exercises/practice/eliuds-eggs/.meta/example.sql
- exercises/practice/eliuds-eggs/create_fixture.sql
- exercises/practice/eliuds-eggs/eliuds-eggs_test.sql
- exercises/practice/eliuds-eggs/test_reporter.sql
- exercises/practice/eliuds-eggs/test_setup.sql
> Auto-format eliuds-eggs .sql files

- exercises/practice/etl/.meta/example.sql
- exercises/practice/etl/create_fixture.sql
- exercises/practice/etl/etl_test.sql
- exercises/practice/etl/test_reporter.sql
- exercises/practice/etl/test_setup.sql
> Auto-format etl .sql files

- exercises/practice/gigasecond/.meta/example.sql
- exercises/practice/gigasecond/create_fixture.sql
- exercises/practice/gigasecond/gigasecond_test.sql
- exercises/practice/gigasecond/test_reporter.sql
- exercises/practice/gigasecond/test_setup.sql
> Auto-format gigasecond .sql files

- exercises/practice/grains/.meta/example.sql
- exercises/practice/grains/create_fixture.sql
- exercises/practice/grains/grains_test.sql
- exercises/practice/grains/test_reporter.sql
- exercises/practice/grains/test_setup.sql
> Auto-format grains .sql files

- exercises/practice/hamming/.meta/example.sql
- exercises/practice/hamming/create_fixture.sql
- exercises/practice/hamming/create_test_table.sql
- exercises/practice/hamming/hamming_test.sql
> Auto-format hamming .sql files

- exercises/practice/hello-world/.meta/example.sql
- exercises/practice/hello-world/create_fixture.sql
- exercises/practice/hello-world/hello-world.sql
- exercises/practice/hello-world/hello-world_test.sql
- exercises/practice/hello-world/test_reporter.sql
- exercises/practice/hello-world/test_setup.sql
> Auto-format hello-world .sql files

- exercises/practice/isbn-verifier/.meta/example.sql
- exercises/practice/isbn-verifier/create_fixture.sql
- exercises/practice/isbn-verifier/create_test_table.sql
- exercises/practice/isbn-verifier/isbn-verifier.sql
- exercises/practice/isbn-verifier/isbn-verifier_test.sql
> Auto-format isbn-verifier .sql files
